## MySQL latest version image
FROM mysql:latest

## Labels
LABEL maintaner="Rober de Avila Abraira"
LABEL website="https://www.linkedin.com/in/rober85/"
LABEL description=""
LABEL version="1.0.0"
LABEL release-date="3-04-2024"

## Exposed port
EXPOSE 3306
